### PR TITLE
abstract-leveldown ~2.1.0

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Also see https://github.com/rvagg/node-leveldown/pull/143 for reference

**Comment by rvagg** [comment]
@ralphtheninja do tests all still pass with this?

**Comment by ralphtheninja** [comment]
Yep! I have tested with io.js `v1.0.2` and node `v0.10.35`.

```
$ t

> leveldown@1.0.1 test /home/lms/src/node-leveldown
> tap test/*-test.js --stderr

ok test/approximate-size-test.js ...................... 16/16
ok test/batch-test.js ................................. 37/37
ok test/chained-batch-test.js ......................... 19/19
ok test/cleanup-hanging-iterators-test.js ............. 20/20
ok test/close-test.js ................................... 7/7
ok test/del-test.js ................................... 12/12
ok test/destroy-test.js ............................... 17/17
ok test/get-test.js ................................... 69/69
ok test/getproperty-test.js ........................... 16/16
ok test/iterator-recursion-test.js ...................... 4/4
ok test/iterator-test.js ............................ 136/136
ok test/leveldown-test.js ............................... 5/5
ok test/make-test.js .................................... 1/1
ok test/open-test.js .................................. 16/16
ok test/port-libuv-fix-test.js .......................... 3/3
ok test/put-get-del-test.js ......................... 144/144
ok test/put-test.js ................................... 10/10
ok test/ranges-test.js .............................. 129/129
ok test/repair-test.js ................................ 11/11
total ............................................... 672/672
```

**Comment by juliangruber** [comment]
lgtm then

**Comment by ralphtheninja** [comment]
I'm merging this now. If there is any project that should follow `abstract-leveldown` it's _this_ project ;)

**Comment by ralphtheninja** [comment]
Ok. Merging. I've also tested it on `0.12` and `iojs@1.6.1`.

**Pull request merged**
