### PR TITLE
nan 1.5 for io.js support

### PR DESCRIPTION
**Pull request by rvagg**
```
node@v0.11.13: PASS wrote output to /tmp/leveldown-dnt-v0.11.13.out
node@v0.10.31: PASS wrote output to /tmp/leveldown-dnt-v0.10.31.out
iojs@v1.0.1-release: PASS wrote output to /tmp/leveldown-dnt-v1.0.1-release.out
```

### CODE REVIEW

**Comment by juliangruber** [comment]
sgtm

**Comment by rvagg** [comment]
sgtm? "seems good to me"? I'll take it anyway!

**Comment by rvagg** [comment]
published as 1.0.1

**Comment by juliangruber** [comment]
@rvagg haha i meant "sounds good to me"

**Pull request merged**
